---
:project: katello
:github_org: katello
:releases:
  :2.3:
    :redmine_release_id: 31
:code_name: Berliner Weisse
:repos:
  :katello:
    :main: true
    :branch: KATELLO-2.3
    :repo: https://github.com/Katello/katello.git
  :katello-installer:
    :branch: KATELLO-2.3
    :repo: https://github.com/Katello/katello-installer.git
  :hammer-cli-katello:
    :branch: 0.0.15
    :repo: https://github.com/Katello/hammer-cli-katello.git
  :katello.org:
    :branch: KATELLO-2.3
    :repo: https://github.com/Katello/katello.org.git
  :katello-misc:
    :branch: KATELLO-2.3
    :repo: https://github.com/Katello/katello-misc.git
:ignores:
