---
:project: foreman
:releases:
  :1.8.0:
    :redmine_release_id: 28
  :1.8.4:
    :redmine_release_id: 84
:repos:
  :foreman:
    :branch: 1.8-stable
    :repo: https://github.com/theforeman/foreman.git
:ignores:
